version: "2.1"
services:
  cra:
    image: node:12.2
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "start:compose"]
    expose:
      - 3000
    volumes:
      - ./package.json:/usr/src/app/package.json:delegated
      - ./package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./public:/usr/src/app/public:delegated
      - ./src:/usr/src/app/src:delegated
    labels:
      - "traefik.enable=true"

      # Configure basic HTTP mapping
      - "traefik.http.routers.cra--80.entrypoints=http80"
      - "traefik.http.routers.cra--80.middlewares=csi-redirect"
      - "traefik.http.routers.cra--80.rule=Host(`cra.${CODE_SERVER_DNS}`)"

      # Configure HTTPS mapping with automatic Letsencrypt certificate management
      - "traefik.http.routers.cra--443.tls=true"
      - "traefik.http.routers.cra--443.entrypoints=http443"
      - "traefik.http.routers.cra--443.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cra--443.rule=Host(`cra.${CODE_SERVER_DNS}`)"
