---
    - name: Upgrade APT
      apt:
        update_cache: yes
    - name: Install basic dependencies
      apt:
        name: "{{item}}"
        state: present
      loop:
        - jq
        - unzip
        - make
        - apache2-utils
        - apt-transport-https
