---
# tasks file for ansible-role-install-pkg-ubuntu
- name: "Include role variables"
  include_vars: "main.yml"

- name: "Gather facts"
  setup:    # equivalent to "gather_facts: yes"

- name: "Wait for any possibly running unattended upgrade to finish"
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: "Update apt package cache"
  apt:
    cache_valid_time: 1200

- name: "Make sure {{ manage_pkg_dependency|length }} needed deb packages are installed"
  apt:
    name: "{{ manage_pkg_dependency }}"
    state: present

- name: "{{ 'Add' if manage_pkg_key_do == 'present' else 'Remove' }} {{ manage_pkg_key|length }} keys from key server to authenticate deb trusted packages"
  apt_key:
    keyserver: "{{ item.url | regex_search('^hkp://.*') | regex_replace('^hkp://([a-z0-9A-Z\\.\\-]+)(:[0-9]+)?$', '\\1') }}"
    id: "{{ item.key }}"
    state: "{{ manage_pkg_key_do }}"
  when: item.url is match('^hkp://.*')
  with_items: "{{ manage_pkg_key }}"
  # Key servers somtimes return an HTTP error
  # Play stubborn here to give it more chances to get executed
  retries: 5
  delay: 15

- name: "{{ 'Add' if manage_pkg_key_do == 'present' else 'Remove' }} {{ manage_pkg_key|length }} keys from url to authenticate deb trusted packages"
  apt_key:
    url: "{{ item.url | regex_search('^http(s)?://.*') }}"
    id: "{{ item.key }}"
    state: "{{ manage_pkg_key_do }}"
  when: item.url is match('^http(s)?://.*')
  with_items: "{{ manage_pkg_key }}"
  # Key servers somtimes return an HTTP error
  # Play stubborn here to give it more chances to get executed
  retries: 5
  delay: 15

- name: "{{ 'Add' if manage_pkg_repo_do == 'present' else 'Remove' }} {{ manage_pkg_repo|length }} apt repositories"
  apt_repository:
    repo: "{{ item }}"
    state: "{{ manage_pkg_repo_do }}"
  with_items: "{{ manage_pkg_repo }}"
  # PPAs somtimes return an HTTP 503 error
  # Play stubborn here to give it more chances to get executed
  retries: 5
  delay: 15

- name: "Wait for any possibly running unattended upgrade to finish"
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: "Refresh apt package cache for new repos"
  apt:
    cache_valid_time: 1200

- name: "{{ 'Add' if manage_pkg_app_do == 'present' else 'Remove' }} {{ manage_pkg_app|length }} deb packages"
  apt:
    name: "{{ manage_pkg_app }}"
    state: "{{ manage_pkg_app_do }}"
    install_recommends: "{{ manage_pkg_app_install_recommends }}"
