---
- name: Add YUM repository
  yum_repository:
    name: packages-microsoft-com-prod
    description: Microsoft .NET RHEL Repository
    baseurl: https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "libicu"
    - "libunwind"
