version: "3.7"

services:
  traefik:
    image: traefik:v2.2
    restart: on-failure
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${CODE_SERVER_CWD}/data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.proxy.loadbalancer.server.port=1337"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.rule=Host(`${CODE_SERVER_DNS}`) && (PathPrefix(`/proxy`) || PathPrefix(`/api`))"
      - "traefik.http.routers.proxy.middlewares=proxy-stripprefix"
      - "traefik.http.middlewares.proxy-stripprefix.stripprefix.prefixes=/proxy"

  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.csi-nginx.loadbalancer.server.port=8082"
      - "traefik.http.routers.csi-nginx-http.entrypoints=web"
      - "traefik.http.routers.csi-nginx-http.rule=Host(`${CODE_SERVER_DNS}`) && PathPrefix(`/`)"
    volumes:
      - ${CODE_SERVER_CWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${CODE_SERVER_CWD}/data/.htpasswd:/basic-auth/.htpasswd
    image: nginx:alpine
    network_mode: host
    restart: on-failure

  app1:
    image: nginx:1.17.6-alpine
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.entrypoints=web"
      - "traefik.http.routers.app1.rule=Host(`${CODE_SERVER_DNS}`) && PathPrefix(`/app1`)"
      - "traefik.http.routers.app1.middlewares=app1-stripprefix"
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.prefixes=/app1"
  app2:
    image: httpd:2.4.41-alpine
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.entrypoints=web"
      - "traefik.http.routers.app2.rule=PathPrefix(`/app2{regex:$$|/.*}`)"
      - "traefik.http.routers.app2.middlewares=app2-stripprefix"
      - "traefik.http.middlewares.app2-stripprefix.stripprefix.prefixes=/app2"

  