version: "3.7"

services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.dummyService.loadbalancer.server.port=1337"
      - "traefik.http.routers.traefik_http.rule=Host(`127.0.0.11`)"
      - "traefik.http.routers.api.rule=Host(`traefik.t1.marcopeg.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$RnbJi4Uh$$PybxuSxXQJQBrq52RDkL2/"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@gopigtail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
#      - "--log.level=DEBUG"
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${TRAEFIK_DATA}/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: traefik:v2.2
    network_mode: host
    restart: on-failure

  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.boris.rule=Host(`vscode.t1.marcopeg.com`)"
      - "traefik.http.routers.boris.entrypoints=web"
      - "traefik.http.routers.boris.middlewares=https_redirect"
      - "traefik.http.routers.boriss.rule=Host(`vscode.t1.marcopeg.com`)"
      - "traefik.http.routers.boriss.entrypoints=websecure"
      - "traefik.http.routers.boriss.tls=true"
      - "traefik.http.routers.boriss.tls.certresolver=myresolver"
      - "traefik.http.routers.boriss.middlewares=https_redirect"
      - "traefik.http.services.boris.loadbalancer.server.port=8082"
    volumes:
      - /home/ubuntu/vscode-ide/compose/nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:alpine
    network_mode: host
    restart: on-failure
