# @TODO: Create tag for the associated volume
#        https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-instance-tag-root-volume/

Description: >

  Keeps up to date a code-ide on AWS

  Last Modified: April 26th, 2020
  Author: Marco Pegoraro <marco.pegoraro@gmail.com>

Parameters:

  S3TemplateRoot:
    Description: How to resolve sub-stack templates
    Type: String

  EC2InstanceType:
    Description: Class of machine to run
    Type: String
    Default: t2.micro
  
  EC2ImageId:
    Description: Image id to use to create the machine
    Type: String

  EC2KeyPairName:
    Description: PEM to access the machine
    Type: String

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref AWS::StackName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2ImageId
      KeyName: !Ref EC2KeyPairName
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref EC2SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: '15'
            DeleteOnTermination: 'true'
            Encrypted: 'true'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

Outputs:
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp

  PrivateIp:
    Value: !GetAtt EC2Instance.PrivateIp