Description: >

  Keeps up to date a code-ide on AWS

  Last Modified: April 26th, 2020
  Author: Marco Pegoraro <marco.pegoraro@gmail.com>

Parameters:

  S3TemplateRoot:
    Description: How to resolve sub-stack templates
    Type: String

  # VPCId:
  #   Description: Target VPC id
  #   Type: String

  # VPCSubnets:
  #   Description: Available subnets
  #   Type: String
  #   Default: subnet-230f2e5e,subnet-2489634e,subnet-ad2410e0

  # EC2ImageId:
  #   Description: AMI ID to run the machine upon
  #   Type: String
  #   Default: ami-05c26ae4789875080

  EC2InstanceType:
    Description: Class of machine to run
    Type: String
    Default: t2.micro
  
  EC2ImageId:
    Description: Image id to use to create the machine
    Type: String

  EC2KeyPairName:
    Description: PEM to access the machine
    Type: String


Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref AWS::StackName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
     
  # NetworkInterface:
  #   Type: AWS::EC2::NetworkInterface
  #   Properties:
  #     GroupSet:
  #       - !Ref SecurityGroup
  #     SourceDestCheck: true

  # EC2Instance:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     ImageId: !Ref EC2ImageId
  #     KeyName: !Ref EC2KeyPairName
  #     InstanceType: !Ref EC2InstanceType
  #     SecurityGroups:
  #     - !Ref EC2SecurityGroup
  #     Tags:
  #       - Key: Name
  #         Value: !Ref AWS::StackName
