- name: This is a hello-world example
  hosts: localhost
  tasks:
    - name: Upgrade APT
      apt:
        update_cache: yes
    - name: Install basic dependencies
      apt:
        name: "{{item}}"
        state: present
      loop:
        - jq
        - unzip
        - make
        - apache2-utils
    - name: Install or upgrade Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes