- name: Installs NVM & Node
  hosts: all

  roles:
    - role: ansible-role-nvm
      # nodejs_version: "8.16.0"
      # nvm_commands:
      #  - "nvm exec default npm install"
      become: true
      become_user: ubuntu