- name: Installs NVM & Node
  hosts: localhost

  roles:
    - role: morgangraphics.ansible_role_nvm
      # nodejs_version: "12"
      # nvm_commands:
      #  - "nvm exec default npm install"
      become: true
      become_user: ubuntu