version: "3.7"

services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.test-ide1-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-ide1-redirect.redirectscheme.permanent=true"

      - "traefik.http.routers.test-ide1.rule=Host(`nginx.${VSCODE_DNS}`)"
      - "traefik.http.routers.test-ide1.entrypoints=web"
      - "traefik.http.routers.test-ide1.middlewares=test-ide1-redirect"

      - "traefik.http.routers.test-ide1-secure.rule=Host(`nginx.${VSCODE_DNS}`)"
      - "traefik.http.routers.test-ide1-secure.entrypoints=websecure"
      - "traefik.http.routers.test-ide1-secure.tls=true"
      - "traefik.http.routers.test-ide1-secure.tls.certresolver=myresolver"

    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: on-failure
